# Generated by Django 5.1.6 on 2025-05-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuxesApp', '0004_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Color of the product', max_length=50, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='Hex code for the color (e.g., #000000)', max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Size of the product (e.g., S, M, L, XL)', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(help_text='Available colors for the product', related_name='products', to='SuxesApp.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(help_text='Available sizes for the product', related_name='products', to='SuxesApp.size'),
        ),
    ]
