# Generated by Django 5.1.6 on 2025-05-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuxesApp', '0005_color_size_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, help_text='Available colors for the product', null=True, related_name='products', to='SuxesApp.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, help_text='Available sizes for the product', null=True, related_name='products', to='SuxesApp.size'),
        ),
    ]
