# Generated by Django 5.1.6 on 2025-05-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuxesApp', '0006_alter_product_colors_alter_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Selected color for the cart item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SuxesApp.color'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, help_text='Selected size for the cart item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SuxesApp.size'),
        ),
    ]
