# Generated by Django 5.1.6 on 2025-05-26 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuxesApp', '0007_cartitem_color_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SuxesApp.address'),
        ),
    ]
