# Generated by Django 5.1.3 on 2025-06-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SuxesApp", "0009_delete_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee",
                    models.PositiveIntegerField(
                        default=0, help_text="Shipping fee for the order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Shipping Fee",
                "verbose_name_plural": "Shipping Fees",
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_status",
            field=models.CharField(
                choices=[
                    (
                        "pending",
                        "Payment Received — payment has been successfully completed ",
                    ),
                    ("Packed", "Packed — packing Order"),
                    ("In transit", "In transit/out for delivery — with the courier "),
                    ("Delivered", "Delivered — oder has reached\xa0your\xa0location."),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
