# Generated by Django 5.2.6 on 2025-10-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuxesApp', '0010_shippingfee_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Email Subscriber',
                'verbose_name_plural': 'Email Subscribers',
            },
        ),
        migrations.CreateModel(
            name='UpcomingMerch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(upload_to='upcoming_merch/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Upcoming Merch',
                'verbose_name_plural': 'Upcoming Merch',
                'ordering': ['release_date'],
            },
        ),
    ]
