# Generated by Django 5.2.6 on 2025-10-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuxesApp', '0011_emailsubscriber_upcomingmerch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingFee',
        ),
    ]
