# Generated by Django 5.2.6 on 2025-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuxesApp', '0012_delete_shippingfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriber',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='discount_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
