# Generated by Django 5.1.6 on 2025-06-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuxesApp', '0008_transaction_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
